sudo: required
language: node_js
node_js:
  - "10.15.3"
script:
  - unset CI
  - npm run build

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY_ID
  bucket: "chefcontinous"
  region: us-west-2
  skip_cleanup: true
  local_dir: build







  